# Generated by Django 2.2.3 on 2019-09-16 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190915_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='location',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='experience',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
