# Generated by Django 2.2.3 on 2019-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190916_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='experience',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
