# Generated by Django 2.2.3 on 2019-09-19 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20190918_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
